### CÁLCULO DE UM SISTEMA DE EQUAÇÕES USANDO O MÉTODO DE GAUSS-SIEDEL

In [3]:
from numpy import array, zeros, diag, diagflat, dot
from numpy.linalg import inv
import numpy as np

##### método de gauss_siedel

In [5]:
def gauss_siedel(A,b,N=2,x=None):
                                                                                                                                 
    if x is None:
        x = zeros(len(A[0]))
                                                                                                                                                                                                                                                                                                               
    D = diagflat(diag(A))
    L = np.tril(A,-1)
    U = np.triu(A,1)
    print('L',L)
    print('U',U)
    print('matriz A :\n',A)
    print('matriz b :\n',b)
    print('matriz D :\n',D)
    print('matriz L :\n',L)
    print('matriz U :\n',U)
    
    G=np.matmul(-inv(D+L),U)
    H=np.matmul(inv(D+L),b)
    print('matriz G :\n',G)
    print('matriz H :\n',H)
    norma=np.max(np.sum(np.abs(G),axis=1))
    print('norma de G :\n',norma)
                                                                                                                                                                        
    for i in range(N):
        x = dot(G,x)+H
        print('x[',i+1,'] = ', x)
    return x


##### entrada de dados e saída de resultados

In [6]:
A = array([[10,2,1],[2,20,2],[-2,3,10]])
b = array([9,-44,22])
inicial = array([1.05,2,3.01])


sol = gauss_siedel(A,b,N=2,x=inicial)

L [[ 0  0  0]
 [ 2  0  0]
 [-2  3  0]]
U [[0 2 1]
 [0 0 2]
 [0 0 0]]
matriz A :
 [[10  2  1]
 [ 2 20  2]
 [-2  3 10]]
matriz b :
 [  9 -44  22]
matriz D :
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 10]]
matriz L :
 [[ 0  0  0]
 [ 2  0  0]
 [-2  3  0]]
matriz U :
 [[0 2 1]
 [0 0 2]
 [0 0 0]]
matriz G :
 [[ 0.    -0.2   -0.1  ]
 [ 0.     0.02  -0.09 ]
 [ 0.    -0.046  0.007]]
matriz H :
 [ 0.9   -2.29   3.067]
norma de G :
 0.30000000000000004
x[ 1 ] =  [ 0.199   -2.5209   2.99607]
x[ 2 ] =  [ 1.104573   -2.6100643   3.20393389]
