##### CÁLCULO DE UM SISTEMA DE EQUAÇÕES USANDO O MÉTODO ITERATIVO GERAL


In [1]:
from numpy import array, zeros, diag, diagflat, dot
from numpy.linalg import inv
import numpy as np

##### método iterativo geral

In [2]:
def iterativo_geral(A,b,n,N,x=None):
                                                                                                                                  
    if x is None:
        x = zeros(len(A[0]))
                                                                                                                                                                                                                                                                                                               
    P=N-A
    print('matriz A :\n',A)
    print('matriz b :\n',b)
    print('matriz N :\n',N)
    print('matriz P :\n',P)
        
    G=np.matmul(inv(N),P)
    H=np.matmul(inv(N),b)
    print('matriz G :\n',G)
    print('matriz H :\n',H)
    norma=np.max(np.sum(np.abs(G),axis=1))
    print('norma de G :\n',norma)
                                                                                                                                                                     
    for i in range(n):
        x = dot(G,x)+H
        print('x[',i+1,'] = ', x)
    return x

##### entrada de dados e saída de resultados

In [3]:
A = array([[1.2,-0.1,-0.2],[-0.15,0.77,0.12],[-0.02,0.22,0.96]])
b = array([0.25,0.1,1.2])
N = array([[1,0,0],[0,1,0],[0,0,1]])
inicial = array([0,0,0])


sol = iterativo_geral(A,b,5,N,x=inicial)

matriz A :
 [[ 1.2  -0.1  -0.2 ]
 [-0.15  0.77  0.12]
 [-0.02  0.22  0.96]]
matriz b :
 [0.25 0.1  1.2 ]
matriz N :
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
matriz P :
 [[-0.2   0.1   0.2 ]
 [ 0.15  0.23 -0.12]
 [ 0.02 -0.22  0.04]]
matriz G :
 [[-0.2   0.1   0.2 ]
 [ 0.15  0.23 -0.12]
 [ 0.02 -0.22  0.04]]
matriz H :
 [0.25 0.1  1.2 ]
norma de G :
 0.5
x[ 1 ] =  [0.25 0.1  1.2 ]
x[ 2 ] =  [0.45   0.0165 1.231 ]
x[ 3 ] =  [0.40785  0.023575 1.25461 ]
x[ 4 ] =  [0.4217095  0.01604655 1.2531549 ]
x[ 5 ] =  [0.41789374 0.01656854 1.25503015]
