### CÁLCULO DE UM SISTEMA DE EQUAÇÕES USANDO O MÉTODO DE JACOBI

In [2]:
from numpy import array, zeros, diag, diagflat, dot
from numpy.linalg import inv
import numpy as np

##### método de jacobi

In [3]:
def jacobi(A,b,N=2,x=None):
                                                                                                                                    
    if x is None:
        x = zeros(len(A[0]))
                                                                                                                                                                                                                                                                                                           
    D = diagflat(diag(A))
    R = A - D
    print('matriz A :\n',A)
    print('matriz b :\n',b)
    print('matriz D :\n',D)
    print('matriz L + U :\n',R)
    Dinv = inv(D)
    G=np.matmul(-Dinv,R)
    H=np.matmul(Dinv,b)
    print('matriz G :\n',G)
    print('matriz H :\n',H)
    norma=np.max(np.sum(np.abs(G),axis=1))
    print('norma de G :\n',norma)
                                                                                                                                                                      
    for i in range(N):
        x = dot(G,x)+H
        print('x[',i+1,'] = ', x)
    return x


##### entrada de dados e saída de resultados

In [4]:
A = array([[10,2,1],[2,20,2],[-2,3,10]])
b = array([9,-44,22])
inicial = array([1.05,2,3.01])


sol = jacobi(A,b,N=2,x=inicial)

matriz A :
 [[10  2  1]
 [ 2 20  2]
 [-2  3 10]]
matriz b :
 [  9 -44  22]
matriz D :
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 10]]
matriz L + U :
 [[ 0  2  1]
 [ 2  0  2]
 [-2  3  0]]
matriz G :
 [[ 0.  -0.2 -0.1]
 [-0.1  0.  -0.1]
 [ 0.2 -0.3  0. ]]
matriz H :
 [ 0.9 -2.2  2.2]
norma de G :
 0.5
x[ 1 ] =  [ 0.199 -2.606  1.81 ]
x[ 2 ] =  [ 1.2402 -2.4009  3.0216]
